source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", ">= 2.0.0.pre.beta.6"
  gem "cloudcannon-jekyll-bookshop", ">= 2.0.0.pre.beta.6"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-postcss-v2'
  gem 'jekyll-local-assign'
end
